name:                halette
version:             0.1.0.0
github:              "githubuser/halette"
license:             BSD3
author:              "soukev"
maintainer:          "soukev@soukev.xyz"
copyright:           "2021 soukev"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/halette#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- gloss-export == 0.1.0.4
- bytestring

library:
  source-dirs: src

executables:
  halette-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - halette

tests:
  halette-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - halette